export const initialFamilyData = [
  // THẾ HỆ 1: Khởi tổ
  {
    id: "1",
    name: "Nguyễn Văn Tổ",
    gender: "male",
    birthYear: "1900",
    deathYear: "1975",
    bio: "Khởi tổ dòng họ, khai hoang lập ấp tại vùng đất phía Nam.",
    parents: [],
    partners: ["2"],
  },
  {
    id: "2",
    name: "Lê Thị Tổ",
    gender: "female",
    birthYear: "1905",
    deathYear: "1980",
    bio: "Mẫu nghi chính thất, thục đức vẹn toàn, Phúc hậu, đoan trang. ",
    parents: [],
    partners: ["1"],
  },

  // THẾ HỆ 2: Các con của Khởi tổ
  {
    id: "3",
    name: "Nguyễn Văn Trưởng",
    gender: "male",
    birthYear: "1925",
    deathYear: "1990",
    bio: "Trưởng tộc đời thứ 2, Lương y nổi tiếng vùng kinh kỳ.",
    parents: ["1", "2"],
    partners: ["4"],
  },
  {
    id: "4",
    name: "Trần Thị Dâu",
    gender: "female",
    birthYear: "1928",
    deathYear: "1995",
    bio: "Phụ giúp chồng bốc thuốc cứu người.",
    parents: [],
    partners: ["3"],
  },
  {
    id: "5",
    name: "Lê Văn Rể",
    gender: "male",
    birthYear: "1928",
    deathYear: "2000",
    bio: "Kiến trúc sư tài ba.",
    parents: ["1", "2"],
    partners: ["6"],
  },
  {
    id: "6",
    name: "Nguyễn Thị Thứ",
    gender: "female",
    birthYear: "1930",
    deathYear: "2005",
    bio: "Định cư tại nước ngoài, luôn hướng về cội nguồn.",
    parents: [],
    partners: ["5"],
  },

  // THẾ HỆ 3: Các cháu nội/ngoại
  {
    id: "7",
    name: "Nguyễn Văn Cháu Đích Tôn",
    gender: "male",
    birthYear: "1955",
    bio: "Giáo sư sử học, đương kim Trưởng tộc.",
    parents: ["3", "4"],
    partners: ["8"],
  },
  {
    id: "8",
    name: "Phạm Thị Hiền",
    gender: "female",
    birthYear: "1960",
    bio: "Giáo viên ưu tú.",
    parents: [],
    partners: ["7"],
  },
  {
    id: "9",
    name: "Nguyễn Văn Cháu Thứ",
    gender: "male",
    birthYear: "1962",
    bio: "Doanh nhân thành đạt.",
    parents: ["3", "4"],
    partners: [],
  },
  {
    id: "10",
    name: "Lê Thị Cháu Ngoại",
    gender: "female",
    birthYear: "1958",
    bio: "Nghệ nhân thêu thùa truyền thống.",
    parents: ["5", "6"],
    partners: [],
  },

  // THẾ HỆ 4: Các chắt
  {
    id: "11",
    name: "Nguyễn Văn Chắt Trai",
    gender: "male",
    birthYear: "1985",
    bio: "Kỹ sư phần mềm (Người tạo ra bản số hóa này).",
    parents: ["7", "8"],
    partners: [],
  },
  {
    id: "12",
    name: "Nguyễn Thị Chắt Gái",
    gender: "female",
    birthYear: "1990",
    bio: "Thạc sĩ kinh tế.",
    parents: ["7", "8"],
    partners: [],
  },
];
